---
- name: Start netsil startup service
  service: name=netsil-startup state=started

- name: Run scale script
  command: "{{ ansible_python_interpreter }} /opt/netsil/latest/bin/install-netsil-apps.py -a scale"
  environment:
    IS_HA: "yes"
