---
- name: Create Netsil AOC master node
  gce:
    instance_names: "netsil-master-{{ instance_id }}"
    machine_type: "{{ master_size }}"
    image: "{{ image }}"
    zone: "{{ zone }}"
    project_id: "{{ gce_project_id }}"
    service_account_email: "{{ gce_service_account_email }}"
    credentials_file: ./gce_credentials.json
    persistent_boot_disk: True
    disk_size: "{{ root_disk_size|int }}"
    network: "{{ network_id|default( 'default', True) }}"
    subnetwork: "{{ subnet_id|default('default', True) }}"
    preemptible: True
    metadata:
      sshKeys:
        - "{{ ssh_user ~ ':' ~ ssh_public_key }}"
  register: netsil_master
  retries: 3
  delay: 5
  until: netsil_master|succeeded

- name: Master node details
  debug:
    var: netsil_master.instance_data[0]

- name: Retrieve public and private IP addresses
  set_fact:
    master_public_ip: "{{ netsil_master.instance_data[0].public_ip }}"
    master_private_ip: "{{ netsil_master.instance_data[0].private_ip }}"
    node_id: "{{ netsil_master.instance_data[0].name }}"

- name: Wait for master SSH
  wait_for:
    port: 22
    host: "{{ master_public_ip }}"
    search_regex: OpenSSH
    delay: 10

- name: Add master to groups netsil-master, netsil-cluster
  add_host:
     hostname: "{{ master_public_ip }}"
     ansible_ssh_host: "{{ master_public_ip }}"
     ip: "{{ master_private_ip }}"
     overlay_listen_ip: "{{ master_private_ip }}"
     ansible_ssh_user: "{{ ssh_user }}"
     ansible_python_interpreter: "{{ python_interpreter }}"
     groups: netsil-master
