---
- name: Remove DCOS install download file
  file: path=/home/core/dcos_generate_config.sh state=absent

- name: Remove DCOS bootstrap file
  file: path=/home/core/genconf/serve/bootstrap state=absent

- name: Remove DCOS genconf Docker image
  shell: "for image in $(docker images -q mesosphere/dcos-genconf); do docker rmi $image; done"

- name: Zero empty space
  shell: dd if=/dev/zero of=/tmpfile || rm -f /tmpfile
  when: build_type != "deploy"
