---
- name: Override ansible_python_interpreter for CoreOS
  set_fact:
    ansible_python_interpreter: "/opt/bin/python"
  when: ansible_os_family == "CoreOS"

- name: Install setup-node.sh for joining workers
  copy: src=setup-node.sh dest=/opt/netsil/latest/bin/setup-node.sh mode=744

- name: Install install-netsil-apps.py for installing netsil apps in marathon
  copy: src=install-netsil-apps.py dest=/opt/netsil/latest/bin/install-netsil-apps.py mode=744

- name: Template netsil startup service
  template: src=netsil-startup.service.j2 dest=/etc/systemd/system/netsil-startup.service

- name: Enable netsil startup service
  service: name=netsil-startup enabled=yes

- name: Start netsil startup service
  service: name=netsil-startup state=started
  when: build_type == "deploy"

- name: Install debug script
  copy: src=grab-debug.sh dest=/opt/netsil/latest/bin/grab-debug.sh mode=755

