---
- name: Check for dcos slave install
  stat: path=/etc/systemd/system/dcos-mesos-slave.service
  register: dcos_slave_install

- name: Install DCOS slave services
  command: bash genconf/serve/dcos_install.sh --disable-preflight slave
  when: dcos_slave_install.stat.exists == false

- name: Find and output the location of dcos-mesos-slave.service
  shell: "find /opt/mesosphere | grep dcos-mesos-slave.service"
  register: dcos_mesos_slave

- name: Link dcos-mesos-slave into /etc/system/systemd
  file: src={{ dcos_mesos_slave.stdout }} dest=/etc/systemd/system/dcos-mesos-slave.service state=link

- name: Link dcos-mesos-slave into /etc/system/systemd/dcos.target.wants. This enables the service.
  file: src={{ dcos_mesos_slave.stdout }} dest=/etc/systemd/system/dcos.target.wants/dcos-mesos-slave.service state=link

- name: Create slave role in /etc
  file: path=/etc/mesosphere/roles/slave state=file

- name: Create slave role in /opt/mesosphere
  file: path=/opt/mesosphere/etc/roles/slave state=directory

- name: Set slave resources
  copy: src=mesos-resources dest=/var/lib/dcos/mesos-resources
