---
- name: Terminate AWS instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    state: absent
    wait: True
    instance_ids: 
      - "{{ instance_id }}"
  register: result

- name: Terminate AWS instance result
  debug:
    msg: "{{ result }}"
