---
- name: Check for dcos master install
  stat: path=/etc/systemd/system/dcos-mesos-master.service
  register: dcos_master_install

- name: Check for dcos download
  stat: path=dcos_generate_config.sh
  register: dcos_download

- name: Retrieve dcos_generate_config
  command: curl -O https://downloads.dcos.io/dcos/EarlyAccess/commit/14509fe1e7899f439527fb39867194c7a425c771/dcos_generate_config.sh
  when:
    - dcos_master_install.stat.exists == false
    - dcos_download.stat.exists == false

- name: Create genconf directory
  file: path=genconf state=directory

- name: Copy over ip-detect script
  template: src=ip-detect.j2 dest=genconf/ip-detect mode=744

- name: Generate dcos config
  template: src="config.yaml.j2" dest="genconf/config.yaml"

  # Generates a CA certificate error
  # get_url: url=https://downloads.dcos.io/dcos/EarlyAccess/commit/14509fe1e7899f439527fb39867194c7a425c771/dcos_generate_config.sh dest=dcos_generate_config.sh

- name: Execute dcos_generate_config
  command: bash dcos_generate_config.sh
  when: dcos_master_install.stat.exists == false

- name: Disable docker restart during dcos install
  replace: dest=genconf/serve/dcos_install.sh regexp="systemctl restart docker" replace=""

- name: Install dcos master
  command: bash genconf/serve/dcos_install.sh master
  when: dcos_master_install.stat.exists == false
