---
- name: Ensure latest symlink exists
  file: src=/opt/netsil/{{ netsil_build_branch }}-{{ netsil_version_number }} dest=/opt/netsil/latest state=link force=yes

- name: Ensure netsil bin directory exists
  file: path=/opt/netsil/latest/bin state=directory

- name: Ensure netsil asset directory exists
  file: path=/opt/netsil/latest/assets state=directory

#- name: Template pull-binaries script
#  template: src=pull-binaries.sh.j2 dest=/opt/netsil/latest/bin/pull-binaries.sh mode=744

- name: Copy over pull-binaries script
  copy: src=pull-binaries.py dest=/opt/netsil/latest/bin/pull-binaries.py mode=744

- name: Pull binaries for all services
  shell: "{{ ansible_python_interpreter }} /opt/netsil/latest/bin/pull-binaries.py"
  environment:
    PWD: "{{ ansible_env.PWD }}"
    APPS_DIR: "/opt/netsil/latest/apps/build/specs"
#  shell: "/opt/netsil/latest/bin/pull-binaries.sh"
