---
- name: Set some build directory vars
  set_fact:
    build_specs_dir: /opt/netsil/{{ netsil_build_branch }}-{{ netsil_version_number }}/apps/build/specs

- name: Template services 
  include: template.yml
  when: build_type == "template"

- name: Clean remote build directory
  file: path={{ build_specs_dir }}/ state=absent

- name: Create remote build specs directory
  file: path={{ build_specs_dir }} state=directory

- name: Copy build specs to remote host
  copy: src={{ apps_dir }}/build/specs/{{ item }}.json dest={{ build_specs_dir }}
  with_items: "{{ pushImages.Pro }}"

