---
- name: Set some build directory vars
  set_fact:
    build_specs_dir: /opt/netsil/{{ netsil_build_branch }}-{{ netsil_version_number }}/apps/build/specs

- name: Create build directories
  local_action: file path={{ item }} state=directory
  with_items:
    - /apps/build/config
    - /apps/build/specs

# TODO: We have to do this because variables aren't being passed to local_action tasks for some reason...
- name: Template services config
  local_action: template src=/apps/config/{{ item }}.json.j2 dest=/apps/build/config/{{ item }}.config.json
  vars:
    tmp_item: "{{ item | regex_replace('-', '_') }}"
    netsil_service_tag: "{{ services_vars['netsil_' + tmp_item + '_tag'] | default(netsil_version_tag) }}"
  with_items: "{{ pushImages.Pro }}"

- name: Template services
  local_action: shell /usr/local/bin/pystache /apps/templates/{{ item }}.mustache /apps/build/config/{{ item }}.config.json > /apps/build/specs/{{ item }}.json
  with_items: "{{ pushImages.Pro }}"

- name: Validate templated jsons
  local_action: shell python -m json.tool /apps/build/specs/{{ item }}.json
  with_items: "{{ pushImages.Pro }}"

- name: Create remote build specs directory
  file: path={{ build_specs_dir }} state=directory

- name: Copy build specs to remote host
  copy: src=/apps/build/specs/{{ item }}.json dest={{ build_specs_dir }}
  with_items: "{{ pushImages.Pro }}"

