---
- name: Set some build directory vars
  set_fact:
    build_specs_dir: /opt/netsil/{{ epoch_build_branch }}-{{ epoch_version_number }}/apps/build/specs

- name: Template services 
  include: template.yml
  when: build_type == "template"

# Note: Not sure if this remote copying is necessary at all. May only be required in building machine images
- name: Clean remote build directory
  file: path={{ build_specs_dir }}/ state=absent
  when: build_type != "template"

- name: Create remote build specs directory
  file: path={{ build_specs_dir }} state=directory
  when: build_type != "template"

- name: Copy build specs to remote host
  copy: src={{ apps_dir }}/build/specs/{{ item }}.json dest={{ build_specs_dir }}
  with_items: "{{ pushImages.Pro }}"
  when: build_type != "template"

