---
- name: Clean build directories
  local_action: file path={{ item }} state=absent
  with_items:
    - "{{ apps_dir }}/build/config/"
    - "{{ apps_dir }}/build/specs/"

- name: Create build directories
  local_action: file path={{ item }} state=directory
  with_items:
    - "{{ apps_dir }}/build/config"
    - "{{ apps_dir }}/build/specs"

- name: Template services config
  local_action: template src={{ apps_dir }}/config/{{ item }}.json.j2 dest={{ apps_dir }}/build/config/{{ item }}.config.json
  vars:
    tmp_item: "{{ item | regex_replace('-', '_') }}"
    epoch_service_tag: "{{ services_vars['epoch_' + tmp_item + '_tag'] | default(epoch_version_tag) }}"
  with_items: "{{ pushImages.Pro }}"
  when: is_ha != "yes"

- name: Template services config for HA
  local_action: template src={{ apps_dir }}/ha-config/{{ item }}.json.j2 dest={{ apps_dir }}/build/config/{{ item }}.config.json
  vars:
    tmp_item: "{{ item | regex_replace('-', '_') }}"
    epoch_service_tag: "{{ services_vars['epoch_' + tmp_item + '_tag'] | default(epoch_version_tag) }}"
  with_items: "{{ pushImages.Pro }}"
  when: is_ha == "yes"

- name: Template mustache
  local_action: shell /usr/local/bin/pystache {{ apps_dir }}/templates/{{ item }}.mustache {{ apps_dir }}/build/config/{{ item }}.config.json > {{ apps_dir }}/build/specs/{{ item }}.json
  with_items: "{{ pushImages.Pro }}"

- name: Validate templated jsons
  local_action: shell python -m json.tool {{ apps_dir }}/build/specs/{{ item }}.json
  with_items: "{{ pushImages.Pro }}"
