---
# This works with the netsil-dcos-gce scripts
- hosts: allnodes
  vars_files:
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/services.yml
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/cluster.yml
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/build.yml
  vars:
    netsil_build_branch: "{{ services_vars['netsil_build_branch'] }}"
    netsil_version_number: "{{ services_vars['netsil_version_number'] }}"
    netsil_commit_hash: "{{ services_vars['netsil_commit_hash'] }}"
    netsil_build_number: "{{ services_vars['netsil_build_number'] }}"
    netsil_version_tag: "{{ services_vars['netsil_version_tag'] }}"
    uri_namespace: "{{ cluster_vars['uri_namespace'] }}"
    is_private_registry: "{{ cluster_vars['is_private_registry'] }}"
    resource_role: "{{ cluster_vars['resource_role'] }}"
    build_env: "{{ cluster_vars['build_env'] }}"
    build_type: "cloud"
    force_pull_image: "{{ cluster_vars['force_pull_image'] }}"
    mesos_master_ip_list: "127.0.0.1"
    ### Start: ansible-specific vars ###
    ansible_user: centos
    ### End: ansible-specific vars ###

  gather_facts: True
  become: yes
  become_user: root

  roles:
    - initialize-dcos-node
    - configure-dcos-node

- hosts: masters
  vars_files:
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/services.yml
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/cluster.yml
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/build.yml
  vars:
    build_env: "{{ cluster_vars['build_env'] }}"
    build_type: "cloud"
    ### Start: ansible-specific vars ###
    ansible_user: centos
    ### End: ansible-specific vars ###

  gather_facts: True
  become: yes
  become_user: root

  roles:
    - configure-dcos-master

- hosts: agents
  vars_files:
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/services.yml
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/cluster.yml
    - /home/centos/netsil-dcos-gce/netsil/netsil-builder/apps/build/vars/build.yml
  vars:
    netsil_build_branch: "{{ services_vars['netsil_build_branch'] }}"
    netsil_version_number: "{{ services_vars['netsil_version_number'] }}"
    netsil_commit_hash: "{{ services_vars['netsil_commit_hash'] }}"
    netsil_build_number: "{{ services_vars['netsil_build_number'] }}"
    netsil_version_tag: "{{ services_vars['netsil_version_tag'] }}"
    uri_namespace: "{{ cluster_vars['uri_namespace'] }}"
    is_private_registry: "{{ cluster_vars['is_private_registry'] }}"
    resource_role: "{{ cluster_vars['resource_role'] }}"
    build_env: "{{ cluster_vars['build_env'] }}"
    build_type: "cloud"
    force_pull_image: "{{ cluster_vars['force_pull_image'] }}"
    ### Start: ansible-specific vars ###
    ansible_user: centos
    ansible_python_interpreter: /usr/bin/python
    ### End: ansible-specific vars ###

  gather_facts: True
  become: yes
  become_user: root

  roles:
    - configure-dcos-slave
    - template-marathon-apps
    - pull-binaries
    - install-startup-scripts

- hosts: netsil-cloud-agent0001
  vars:
    ansible_python_interpreter: /usr/bin/python
    
  gather_facts: True
  become: yes
  become_user: root

  roles:
    - install-cloud-apps
