---
- hosts: agents

  vars_files:
    - /apps/build/vars/services.yml
    - /apps/build/vars/cluster.yml
    - /apps/build/vars/build.yml

  vars:
    netsil_build_branch: "{{ services_vars['netsil_build_branch'] }}"
    netsil_version_number: "{{ services_vars['netsil_version_number'] }}"
    netsil_commit_hash: "{{ services_vars['netsil_commit_hash'] }}"
    netsil_build_number: "{{ services_vars['netsil_build_number'] }}"
    netsil_version_tag: "{{ services_vars['netsil_version_tag'] }}"
    uri_namespace: "{{ cluster_vars['uri_namespace'] }}"
    is_private_registry: "{{ cluster_vars['is_private_registry'] }}"
    resource_role: "{{ cluster_vars['resource_role'] }}"
    build_env: "{{ cluster_vars['build_env'] }}"
    force_pull_image: "{{ cluster_vars['force_pull_image'] }}"
    mesos_master_ip_list: "127.0.0.1"
    is_ha: "{{ lookup('env', 'IS_HA') or cluster_vars['is_ha'] }}"

  roles:
    - template-marathon-apps
