---
- name: Create genconf directory
  file: path=genconf state=directory

- name: Copy over ip-detect script
  copy: src=ip-detect dest=genconf/ip-detect mode=744

- name: Generate dcos config
  template: src="config.yaml.j2" dest="genconf/config.yaml"

- name: Retrieve dcos_generate_config
  command: curl -O https://downloads.dcos.io/dcos/EarlyAccess/commit/14509fe1e7899f439527fb39867194c7a425c771/dcos_generate_config.sh

  # Generates a CA certificate error
  # get_url: url=https://downloads.dcos.io/dcos/EarlyAccess/commit/14509fe1e7899f439527fb39867194c7a425c771/dcos_generate_config.sh dest=dcos_generate_config.sh

- name: Execute dcos_generate_config
  command: bash dcos_generate_config.sh

- name: Install dcos master
  command: bash genconf/serve/dcos_install.sh master
