- name: Stop and disable firewalld service
  service: name=systemd-coredump.socket state=stopped enabled=no
  ignore_errors: true

- name: Add epel repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: yes

- rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- yum: name=jq
