---
- name: Include CoreOS tasks
  include: configure-coreos.yml
  when: ansible_os_family == "CoreOS"

- name: Further disable by setting the conf file
  copy: src=coredump.conf dest=/etc/systemd/coredump.conf

# Install docker-healthcheck
- name: Install docker-healthcheck script
  copy: src=docker-healthcheck dest=/opt/netsil/latest/bin/docker-healthcheck mode=755

- name: Install docker-healthcheck service
  copy: src=docker-healthcheck.service dest=/etc/systemd/system/docker-healthcheck.service

- name: Enable docker-healthcheck service
  service: name=docker-healthcheck.service enabled=yes

- name: Start docker-healthcheck service
  service: name=docker-healthcheck.service state=started
  when: build_type == "deploy"

# Cleanup exited containers and dangling volumes on a timer
- name: Install docker-cleanup.service 
  copy: src=docker-cleanup.service dest=/etc/systemd/system/docker-cleanup.service

- name: Install docker-cleanup.timer 
  copy: src=docker-cleanup.timer dest=/etc/systemd/system/docker-cleanup.timer

- name: Start/enable docker-cleanup.timer
  service: name=docker-cleanup.timer state=started enabled=yes

# Install logrotate
- name: Ensure conf directory exists
  file: path=/opt/netsil/{{ netsil_build_branch }}-{{ netsil_version_number }}/etc state=directory mode=0755

- name: Install docker-logrotate conf
  copy: src=docker-logrotate.conf dest=/opt/netsil/latest/etc/docker-logrotate.conf

- name: Install docker-logrotate.service 
  copy: src=docker-logrotate.service dest=/etc/systemd/system/docker-logrotate.service

- name: Install docker-logrotate.timer 
  copy: src=docker-logrotate.timer dest=/etc/systemd/system/docker-logrotate.timer

- name: Start/enable docker-logrotate.timer
  shell: "systemctl start docker-logrotate.timer && systemctl enable docker-logrotate.timer"

- name: Restart DCOS services
  service: name={{ item }} state=restarted
  with_items:
    - dcos.target
  when: build_type == "deploy"
